---
title: "BIOL 381"
author: "Cai McCann"
date: "Spring 2020"
output: 
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

--------------------------------------------------------------------------------

## Homework 1/2

[Homework 1 Typora html](Typora_Homework_1.html)

[Homework 1 Typora PDF](Typora_Homework_1.pdf)

## Homework 3
[Homework_3](Homework_3.html)

## Homework 4
[Homework_4](Homework_4.html)

## Homework 5
[Homework_5](Homework_5.html)

## Homework 6
[Homework_6](Homework_6.html)

## Homework 7
[Homework_7](Homework_7.html)

## Homework 8
[Homework_8](Homework_8.html)

## Homework 9
[Homework_9](Homework_9.html)

## Homework 10
[Homework_10](Homework_10.html)

## Homework 11
[Homework_11](Homework_11.html)

## Homework 12
[Homework_12](Homework_12.html)


## Other Notes: 
 
Important note: for the purposes of demonstrating the wide variety of capabilities in R, I used study data from the Vermont Diabetes Information System
(VDIS) study. VDIS reports on the study design and baseline characteristics of the population, and is well accepted by patients, providers, and laboratory staff. These results also compare favorably to recent national reports.

Here is an article about the study, in case you’d like to learn more about these data <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2518939/>

*Citation: MacLean, C. D., Littenberg, B., Gagnon, M., Reardon, M., Turner, P. D., & Jordan, C. (2004). The Vermont Diabetes Information System (VDIS): Study Design and Subject Recruitment for a Cluster Randomized Trial of a Decision Support System in a Regional Sample of Primary Care Practices. Clinical Trials (London, England), 1(6), 532–544.*

## Acknowledgements: 

Thank you, Lauren Ash, for an eye-popping prettydoc theme and your help during labs!

A special thanks to Dr. Gotelli for his expertise in R and support for the BIOL 381 course. 

